name: 2019_ml_ocean
channels:
- defaults
- conda-forge
dependencies:
- scipy
- numpy
- scikit-learn
- matplotlib
- statsmodels
- pandas
- numba
- h5py
- xarray
- pytables
- dask
- cartopy
- seaborn
- jupyterlab
- ipykernel
- GPy
- tensorflow        # Tensor library (Anaconda CPU enhanced)
- pip:
  - gpflow          # tensor GP library