name: 2019_ml_ocean_gpu
channels:
- defaults
- conda-forge
dependencies:
- scipy
- numpy
- scikit-learn
- matplotlib
- statsmodels
- pandas
- numba
- h5py
- xarray
- pytables
- dask
- cartopy
- seaborn
- jupyterlab
- ipykernel
- GPy
- tensorflow-gpu
- pip:
  - gpflow          # tensor GP library
  # - tensorflow-gpu  # Tensor library
