name: 2019_ml_ocean
channels:
- defaults
- conda-forge
dependencies:
- scipy
- numpy
- scikit-learn
- matplotlib
- pandas
- numba
- h5py
- xarray
- pytables
- dask
- cartopy
- seaborn
- jupyterlab
- ipykernel
- GPy
- pip:
  - tensorflow-gpu  # Tensor library
  - gpflow          # tensor GP library