name: 2019_ml_ocean
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
# Standard Python Libraries
- scipy
- numpy
- pandas
# Plotting Libraries
- matplotlib
- cartopy
- seaborn
# ML Libraries
- scikit-learn
- statsmodels
# Data Structures
- h5py
- xarray
# Logistics
- ipykernel
# Special ML Libraries
- GPy
# Geoprocessing
- geopandas
- shapely
- descartes
# Tensor Libraries
- pip:
  - tensorflow==2.0.0
  - tensorflow-probability==0.8
  - -e "git+https://github.com/GPflow/GPflow.git@develop-2.0#egg=gpflow"