# Project information
site_name: ML 4 Ocean Applications
site_description: ML 4 Ocean Applications
site_author: J. Emmanuel Johnson
site_url: https://IPL-UV.github.io/ml4ocean

# Repository
repo_name: IPL-UV/ml4ocean
repo_url: https://github.com/IPL-UV/ml4ocean

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: source code pro
    code: source code pro

plugins:
  - search
  - mknotebooks:
      execute: false
      write_markdown: true
      timeout: 600

# Copyright
copyright: Copyright &copy; 2020 ISP-UV

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
    - javascripts/extra.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


extra:
  # disqus: XHR39t5kZv
  social:
    # - type: 'envelope'
    #   link: 'http://www.shortwhale.com/ericmjl'
    - icon: fontawesome/brands/github
      link: 'https://github.com/IPL-UV'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/isp'
    - icon: fontawesome/solid/globe
      link: 'https://isp.uv.es'
  